name: 'Actency news configuration grid'
description: 'Provides configuration files for grid views.'
type: module
core: 8.x
dependencies:
  - act_news
  - better_exposed_filters
  - smart_trim
version: 8.x-1.0
