name: 'Actency news configuration list'
description: 'Provides configuration files for list views.'
type: module
core: 8.x
dependencies:
  - act_news
  - better_exposed_filters
  - smart_trim
  - system
version: 8.x-1.0
